### ISSUE TITLE
Meltano without a catalog file

### ISSUE THREAD

**Issue by oofaish** [singer-io/tap-mysql#154]
Simply following the steps specified here: 

[https://hub.meltano.com/extractors/tap-mysql/](https://hub.meltano.com/extractors/tap-mysql/)
leads to an exception being raised in the `meltano config tap-mysql test` step 
``` only INCREMENTAL, LOG_BASED, and FULL TABLE replication methods are supported ```

I don't see a way of specifying the replication method without passing in a catalog file, so completely by-passing the "simplified" Meltano YAML file. I also get a similar error by adding a couple of simple selects to the YAML file.

Is that the expected behaviour? i.e. are the `Installation and configuration` steps are not quite right and tap-mysql always requires the catalog to be passed in using a file?

Many thanks

Ali

**Comment by pnadolny13** [comment]
@oofaish this sounds like it might be Meltano specific problem. I suggested a fix to the default Meltano setting for this tap so  it doesnt raise that exception.

**Comment by oofaish** [comment]
thank you @pnadolny13! I ll close this PR!
