### ISSUE TITLE
"type": "STATE", "value": {"currently_syncing": null}}

### ISSUE THREAD

**Issue by MuhammadAdeelUsman** [singer-io/tap-mysql#61]
I'm trying to understand how singer code work. I have created the same table as in example but as i ran the following command i get the following message. i don't understand where the output file is generated. I have read documentation couple of times. Can anyone help me to sort it out   
` tap-mysql -c config.json --properties properties.json
/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py:161: Warning: (1158, 'Got an error reading communication packets')
  while self.nextset():
INFO Server Parameters: version: 10.2.11-MariaDB-10.2.11+maria~trusty-log, wait_timeout: 2700, innodb_lock_wait_timeout: 2700, max_allowed_packet: 16777216, interactive_timeout: 28800
{"type": "STATE", "value": {"currently_syncing": null}}`

**Comment by briansloane** [comment]
@MuhammadAdeelUsman I recommend heading over to the Singer Slack group to discuss this with the active developer community.

https://singer-slackin.herokuapp.com/

**Comment by MuhammadAdeelUsman** [comment]
Thanks for your suggestion. i'm going to close this issue
