### ISSUE TITLE
Documentation example not working with RDS and typos

### ISSUE THREAD

**Issue by thompdre84** [singer-io/tap-mysql#73]
1. I spent the better part of a day trying to get tap-mysql to pull from a AWS-RDS MySQL instance. I was able to discover the DB just fine but was never getting any records when trying to sync. The current examples in the documentation do not match what I had to do to finally get it working.

The example shows that the following is how one would select a table for replication:
`{
  "selected": "true",
  "properties": {
    "likes_getting_petted": {
      "selected": "true",
      "inclusion": "available",
      "type": [
        "null",
        "boolean"
      ]
    },
    "name": {
      "selected": "true",
      "maxLength": 255,
      "inclusion": "available",
      "type": [
        "null",
        "string"
      ]
    },`

My own investigation and instrumentation of the source code revealed that the source code specifically looks for `"metadata":` followed by an empty breadcrumb list `"breadcrumb": []`. It is in that portion of the properties/catalog file that it ultimately searches for `"selected": true`. Here is a working example from my own code: 
`"metadata": [
       {
          "breadcrumb": [],
          "metadata": {
            "selected": true,
            "replication-method": "FULL_TABLE",
            "selected-by-default": false,
            "database-name": "pimcore",
            "row-count": 76,
            "is-view": false,
            "table-key-properties": [
              "id"
            ]
          }
        },`

2. The error messaging for a failed replication type has a typo. The current message reads as, "Exception: only INCREMENTAL, LOG_BASED, and FULL TABLE replication methods are supported"

There is no "FULL TABLE", the correct value is "FULL_TABLE".

**Comment by KAllan357** [comment]
Thanks for catching this. I believe this is the offending code that needs a tweak:

https://github.com/singer-io/tap-mysql/blob/ec1aba6f505cb714773d8eefed7a2ab5164e7ac1/tap_mysql/__init__.py#L653

**Comment by dmosorast** [comment]
Addressed in #76, closing.
