### ISSUE TITLE
Tap-MySQL Incompatible with MySQL version 8

### ISSUE THREAD

**Issue by cfraleig** [singer-io/tap-mysql#74]
Looks like most of the problems are coming from dependencies on an older version of the PyMySQL connector. Was getting charset error, and error with authentication.

**Comment by nick-mccoy** [comment]
Hi @cfraleig, thanks for opening this.  If you want to take care of this, you could try updating the version of PyMySQL to the most recent version, running the tap locally to verify that it fixes the error(s), and submitting a PR with the change and some test logs.

**Comment by nelsonic1** [comment]
I managed to get around handshake issues with MySQL 8 by running `pip install --upgrade PyMySQL` in my virtualenvironment and then updating `requires.txt` to include the new version number. `PyMySQL 0.9.2` works fine so far although I haven't done much yet. For reference I am running `MySQL 8.0.12 Homebrew`.

**Comment by dmosorast** [comment]
PyMySQL has since been upgraded to 0.9.3, so this sounds like it's good to close.
