### ISSUE TITLE
showed {"type": "STATE", "value": {"currently_syncing": null}} even though table rows not empty 

### ISSUE THREAD

**Issue by carillpower** [singer-io/tap-mysql#75]
Hi, I would like to check if I miss anything in my properties.json file as when I test it keeps on shown like above instead of the value in JSON format. Below are the content inside 

`
{
    "streams": [
      {
      "replication_method": "FULL_TABLE",
      "replication_key": "id",
      "key_properties": [
        "id"
      ],
        "tap_stream_id": "quiz-animal",
        "table_name": "animal",
        "schema": {
          "properties": {
            "id": {
              "inclusion": "automatic",
              "minimum": -2147483648,
              "maximum": 2147483647,
              "type": [
                "null",
                "integer"
              ]
            },
            "name": {
              "inclusion": "available",
              "maxLength": 10,
              "type": [
                "null",
                "string"
              ]
            },
            "likes": {
              "inclusion": "available",
              "minimum": -2147483648,
              "maximum": 2147483647,
              "type": [
                "null",
                "integer"
              ]
            }
          },
          "type": "object"
        },
        "stream": "animal",
        "metadata": [
          {
            "breadcrumb": [],
            "metadata": {
              "selected-by-default": false,
              "database-name": "quiz",
              "row-count": 6,
              "is-view": false,
              "table-key-properties": [
                "id"
              ]
            }
          },
          {
            "breadcrumb": [
              "properties",
              "id"
            ],
            "metadata": {
              "selected-by-default": true,
              "sql-datatype": "int(11)"
            }
          },
          {
            "breadcrumb": [
              "properties",
              "name"
            ],
            "metadata": {
              "selected-by-default": true,
              "sql-datatype": "varchar(10)"
            }
          },
          {
            "breadcrumb": [
              "properties",
              "likes"
            ],
            "metadata": {
              "selected-by-default": true,
              "sql-datatype": "int(11)"
            }
          }
        ]
      }
    ]
}
`
Kindly anyone who've face this let me know if im missing something.

Appreciate on any suggestion.

**Comment by carillpower** [comment]
Update better format

``` {
    "streams": [
      {
      "replication_method": "FULL_TABLE",
      "replication_key": "id",
      "key_properties": [
        "id"
      ],
        "tap_stream_id": "quiz-animal",
        "table_name": "animal",
        "schema": {
          "properties": {
            "id": {
              "inclusion": "automatic",
              "minimum": -2147483648,
              "maximum": 2147483647,
              "type": [
                "null",
                "integer"
              ]
            },
            "name": {
              "inclusion": "available",
              "maxLength": 10,
              "type": [
                "null",
                "string"
              ]
            },
            "likes": {
              "inclusion": "available",
              "minimum": -2147483648,
              "maximum": 2147483647,
              "type": [
                "null",
                "integer"
              ]
            }
          },
          "type": "object"
        },
        "stream": "animal",
        "metadata": [
          {
            "breadcrumb": [],
            "metadata": {
              "selected-by-default": false,
              "database-name": "quiz",
              "row-count": 6,
              "is-view": false,
              "table-key-properties": [
                "id"
              ]
            }
          },
          {
            "breadcrumb": [
              "properties",
              "id"
            ],
            "metadata": {
              "selected-by-default": true,
              "sql-datatype": "int(11)"
            }
          },
          {
            "breadcrumb": [
              "properties",
              "name"
            ],
            "metadata": {
              "selected-by-default": true,
              "sql-datatype": "varchar(10)"
            }
          },
          {
            "breadcrumb": [
              "properties",
              "likes"
            ],
            "metadata": {
              "selected-by-default": true,
              "sql-datatype": "int(11)"
            }
          }
        ]
      }
    ]
}
```

**Comment by zedyap** [comment]
Hi All, 

I have the same issue where sync mode would just return me the following result:

`{"type": "STATE", "value": {"currently_syncing": null}} `

The following are my properties.json:
`
 {
  "streams": [
    {
	 "replication_method": "FULL_TABLE",
      "replication_key": "id",
      "key_properties": [
        "id"
      ],
      "tap_stream_id": "animal-animals",
      "table_name": "animals",
      "metadata": [
        {
          "metadata": {
			"row-count": 0,
            "database-name": "animal",
            "table-key-properties": [
              "id"
            ],
            "is-view": false,
            "selected-by-default": false
          },
          "breadcrumb": []
        },
        {
          "metadata": {
            "sql-datatype": "int(11)",
            "selected-by-default": true
          },
          "breadcrumb": [
            "properties",
            "id"
          ]
        },
        {
          "metadata": {
            "sql-datatype": "varchar(45)",
            "selected-by-default": true
          },
          "breadcrumb": [
            "properties",
            "name"
          ]
        },
        {
          "metadata": {
            "sql-datatype": "tinyint(1)",
            "selected-by-default": true
          },
          "breadcrumb": [
            "properties",
            "likes_getting_petted"
          ]
        }
      ],
      "schema": {
        "type": "object",
		"selected": true,
        "properties": {
          "name": {
		  "selected": "true",
            "type": [
              "null",
              "string"
            ],
            "maxLength": 45,
            "inclusion": "available"
          },
          "likes_getting_petted": {
		  "selected": true,
            "type": [
              "null",
              "boolean"
            ],
            "inclusion": "available"
          },
          "id": {
		  "selected": true,
            "minimum": -2147483648,
            "type": [
              "null",
              "integer"
            ],
            "maximum": 2147483647,
            "inclusion": "automatic"
          }
        }
      },
      "stream": "animals"
    }
  ]
}{
  "streams": [
    {
	 "replication_method": "FULL_TABLE",
      "replication_key": "id",
      "key_properties": [
        "id"
      ],
      "tap_stream_id": "animal-animals",
      "table_name": "animals",
      "metadata": [
        {
          "metadata": {
			"row-count": 0,
            "database-name": "animal",
            "table-key-properties": [
              "id"
            ],
            "is-view": false,
            "selected-by-default": false
          },
          "breadcrumb": []
        },
        {
          "metadata": {
            "sql-datatype": "int(11)",
            "selected-by-default": true
          },
          "breadcrumb": [
            "properties",
            "id"
          ]
        },
        {
          "metadata": {
            "sql-datatype": "varchar(45)",
            "selected-by-default": true
          },
          "breadcrumb": [
            "properties",
            "name"
          ]
        },
        {
          "metadata": {
            "sql-datatype": "tinyint(1)",
            "selected-by-default": true
          },
          "breadcrumb": [
            "properties",
            "likes_getting_petted"
          ]
        }
      ],
      "schema": {
        "type": "object",
		"selected": true,
        "properties": {
          "name": {
		  "selected": "true",
            "type": [
              "null",
              "string"
            ],
            "maxLength": 45,
            "inclusion": "available"
          },
          "likes_getting_petted": {
		  "selected": true,
            "type": [
              "null",
              "boolean"
            ],
            "inclusion": "available"
          },
          "id": {
		  "selected": true,
            "minimum": -2147483648,
            "type": [
              "null",
              "integer"
            ],
            "maximum": 2147483647,
            "inclusion": "automatic"
          }
        }
      },
      "stream": "animals"
    }
  ]
}`

Any help will be much appreciated

**Comment by dmosorast** [comment]
@zedyap I suspect this is the same reason as the issue being experienced by @carillpower. To elaborate on my answer above, the portion of the metadata that I am referring to should look like this:

```
...
            "table_name": "animals",
            "metadata": [
                {
                    "metadata": {
                        "row-count": 0,
                        "database-name": "animal",
                        "table-key-properties": [
                            "id"
                        ],
                        "is-view": false,
                        "selected-by-default": false,
                        "selected": true,
                        "replication-method": "FULL_TABLE"
                    },
                    "breadcrumb": []
                },
...
```

Note the addition of `"selected": true` and `"replication-method": "FULL_TABLE"` to this piece of metadata. These are the values that the tap will use to determine if the table is selected (see related code [here](https://github.com/singer-io/tap-mysql/blob/master/tap_mysql/sync_strategies/common.py#L36)) and what strategy to use to request data from the table (see related code [here](https://github.com/singer-io/tap-mysql/blob/master/tap_mysql/__init__.py#L636-L653)). Hope this helps clarify. Let me know if you run into any other issues.

**Comment by zedyap** [comment]
Hi @dmosorast ,

Thank you for your help, and I manage to get it working using your suggestion. I guess the documentation needs to be updated in this following URL:

- https://github.com/singer-io/tap-mysql

Thank you again for your help.
Cheers

**Comment by carillpower** [comment]
Thanks @dmosorast , works for me so far.. thumbs up for the quick response ! 👍

**Comment by dmosorast** [comment]
No problem, I have a PR to adjust the wording of the README. Closing this issue for now.

**Comment by jane-booky** [comment]
Thanks for the answers. I still miss these facts though / or not clear enough even after the doc update (maybe it's just me). 
I'm working on tap-postgres. Is it possible to like link the mysql doc if it's almost the same? I saw a request but doesnt seem like it was done.

Thanks
