### ISSUE TITLE
What updates the state.json file?

### ISSUE THREAD

**Issue by mattarderne** [singer-io/tap-mysql#88]
Should running the tap in sync mode update the `state.json` file? Or do I need to manually pipe the last line to the state file as a bookmark?

**Comment by luandy64** [comment]
Nothing updates the `state.json` file, so you would have to manually do some work here. I would follow the command under the fourth bullet in this list in [the docs](https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-a-singer-tap-with-a-singer-target).

**Comment by mattarderne** [comment]
Ah, thanks @luandy64, appreciate the guidance.
